//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LyncStream.QQR.Logic.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Contact Request")]
        public string ContactSubject {
            get {
                return ((string)(this["ContactSubject"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<!DOCTYPE html>
<!--[if lt IE 7]>      <html class=""no-js lt-ie9 lt-ie8 lt-ie7""> <![endif]-->
<!--[if IE 7]>         <html class=""no-js lt-ie9 lt-ie8""> <![endif]-->
<!--[if IE 8]>         <html class=""no-js lt-ie9""> <![endif]-->
<!--[if gt IE 8]><!-->
<html class=""no-js"">
<!--<![endif]-->
<head>
    <meta charset=""utf-8"">
    <meta http-equiv=""X-UA-Compatible"" content=""IE=edge,chrome=1"">
    <title>Schedule Request</title>
    <meta name=""description"" content="""">
    <meta name=""viewport"" content=""width=device-width"">
</head>
<body>
    <!--[if lt IE 7]>
            <p class=""chromeframe"">You are using an <strong>outdated</strong> browser. Please <a href=""http://browsehappy.com/"">upgrade your browser</a> or <a href=""http://www.google.com/chromeframe/?redirect=true"">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->
    <!--[if lt IE 9]>
			<script src=""http://html5shim.googlecode.com/svn/trunk/html5.js""></script>
		<![endif]-->
    <!--[if gte IE 9]>

    <link href=""http://qqr.lyncpost.com/Content/Custom/notie9.css"" rel=""stylesheet"" />
		  	
		<![endif]-->
    <p>{0} from {1} has requested to be contacted.  They can be contacted by email at {2}. Please see the below message for more details.</p>
    <p>{3}</p>

</body>
</html>
")]
        public string ContactBody {
            get {
                return ((string)(this["ContactBody"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("info@quinnsreporting.com")]
        public string ContactToAddress {
            get {
                return ((string)(this["ContactToAddress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Schedule Request")]
        public string ScheduleSubject {
            get {
                return ((string)(this["ScheduleSubject"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<!DOCTYPE html>\r\n<!--[if lt IE 7]>      <html class=\"no-js lt-ie9 lt-ie8 lt-ie7\">" +
            " <![endif]-->\r\n<!--[if IE 7]>         <html class=\"no-js lt-ie9 lt-ie8\"> <![endi" +
            "f]-->\r\n<!--[if IE 8]>         <html class=\"no-js lt-ie9\"> <![endif]-->\r\n<!--[if " +
            "gt IE 8]><!-->\r\n<html class=\"no-js\">\r\n<!--<![endif]-->\r\n<head>\r\n    <meta charse" +
            "t=\"utf-8\">\r\n    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n" +
            "    <title>Schedule Request</title>\r\n    <meta name=\"description\" content=\"\">\r\n " +
            "   <meta name=\"viewport\" content=\"width=device-width\">\r\n    \r\n</head>\r\n<body>\r\n " +
            "   <!--[if lt IE 7]>\r\n            <p class=\"chromeframe\">You are using an <stron" +
            "g>outdated</strong> browser. Please <a href=\"http://browsehappy.com/\">upgrade yo" +
            "ur browser</a> or <a href=\"http://www.google.com/chromeframe/?redirect=true\">act" +
            "ivate Google Chrome Frame</a> to improve your experience.</p>\r\n        <![endif]" +
            "-->\r\n    <!--[if lt IE 9]>\r\n\t\t\t<script src=\"http://html5shim.googlecode.com/svn/" +
            "trunk/html5.js\"></script>\r\n\t\t<![endif]-->\r\n    <!--[if gte IE 9]>\r\n\t\t\r\n\t\t<![endi" +
            "f]-->   \r\n\r\n   \r\n                <p>{0} from {1} has requested to schedule a dep" +
            "osition.  Please see the below message for more details.</p>\r\n\r\n                " +
            "<h3>Contact Information</h3>\r\n\r\n                <label>Name of Attorney</label><" +
            "br/>\r\n                <label>{1}</label><br/><br/>\r\n\r\n                <label>Pho" +
            "ne Number</label><br/>\r\n                <label>{2}</label><br/><br/>\r\n\r\n        " +
            "        <label>Contact Name</label><br/>\r\n                <label>{0}</label><br/" +
            "><br/>\r\n\r\n                <label>Email</label><br/>\r\n                <label>{3}<" +
            "/label><br/><br/>                \r\n\r\n                <h3>Delivery Requirements</" +
            "h3>\r\n                <label>Turnaround Time</label><br/>\r\n                <label" +
            ">{4}</label><br/><br/>\r\n\r\n                <label>Additional Information or Comme" +
            "nts</label><br/>\r\n                <label>{5}</label><br/><br/>\r\n\r\n              " +
            "  <h3>Deposition Information</h3>\r\n                <label>Date/Time</label><br/>" +
            "\r\n                <label>{6}</label><br/><br/>\r\n\r\n                <label>Estimat" +
            "ed length of deposition/trial</label><br/>\r\n                <label>{7}</label><b" +
            "r/><br/>\r\n\r\n                <label>Place of Deposition/Trial</label><br/>\r\n     " +
            "           <label>{8}</label><br/><br/>\r\n\r\n                <label>Address</label" +
            "><br/>\r\n                <label>{9}</label><br/><br/>\r\n\r\n                <label>C" +
            "ity</label><br/>\r\n                <label>{10}</label><br/><br/>\r\n\r\n             " +
            "   <label>State</label><br/>\r\n                <label>{11}</label><br/><br/>\r\n\r\n " +
            "               <label>Video</label><br/>\r\n                <label>{12}</label><br" +
            "/><br/>\r\n\r\n                <label>File Attached</label><br/>\r\n                <l" +
            "abel>{13}</label><br/>  \r\n\r\n</body>\r\n</html>\r\n")]
        public string ScheduleBody {
            get {
                return ((string)(this["ScheduleBody"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rtbattreall@cox.net")]
        public string ScheduleToAddress {
            get {
                return ((string)(this["ScheduleToAddress"]));
            }
        }
    }
}
